spring:
  application:
    name: intranet
  
  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/intranet
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Server Configuration
server:
  port: 8080

# JWT Configuration
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 horas em milissegundos
